---
- name: Install avahi package
  apt:
    name: avahi-daemon
    state: present
    update_cache: true

- include: delete-not-published-services.yml

- name: Setup avahi services
  template:
    src: avahi-service.j2
    dest: "/etc/avahi/services/{{ item.file }}.service"
    owner: root
    group: root
    mode: '0644'
  with_items: "{{ avahi_published_services }}"
  notify: Reload avahi daemon

- name: Enable avahi deamon
  service:
    name: avahi-daemon
    enabled: true
  register: avahi_daemon_service
  changed_when: avahi_daemon_service.changed
    or avahi_daemon_service.status.SubState != 'running'
  notify: Start avahi daemon
  when: not (
    molecule_docker_environment is defined
    and molecule_docker_environment | bool
    )

- name: Start systemd-managed service
  meta: flush_handlers
