Vagrant.configure("2") do |config|
#   config.vm.box = "ubuntu/xenial64"
  config.vm.box = "ubuntu/bionic64"
#   config.vm.box = "ubuntu/focal64"

  config.vm.network "private_network", ip: "192.168.33.61"

  config.vm.provider "virtualbox" do |v|
    v.name = "ansible_avahi"
    v.memory = 1024
    v.cpus = 2
  end
end
