---
- name: Converge
  hosts: all
  become: true

  roles:
    - role: ansible-avahi
      avahi_published_services:
        - file: timemachine
          name: '%h'
          services:
            - type: _afpovertcp._tcp
              port: 548
            - type: _device-info._tcp
              port: 0
              txt_records:
                - model=TimeCapsule
        - file: samba
          name: samba on %h
          services:
            - type: _smb._tcp
              port: 445
